language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
before_script:
  - npm install
cache:
  directories:
    - node_modules
build:
  webpack
test:
  npm test
