/**
 * @file Exports the protocol used to mediate goontube actions between client, server, and Redux.
 * @since 1.0.0
 */
export default {
    /* Banner */
    BANNER_LIST_UPDATE:         'BANNER_LIST_UPDATE',
    BANNER_NEW_BANNER:          'BANNER_NEW_BANNER',
    BANNER_NEW_RANDOM_BANNER:   'BANNER_NEW_RANDOM_BANNER',

    /* Authentication */
    RESET_LOGIN_FAILURE:        'RESET_LOGIN_FAILURE',
    AUTHENTICATION_ATTEMPT:     'AUTHENTICATION_ATTEMPT',
    AUTHENTICATION_RESPONSE:    'AUTHENTICATION_RESPONSE',
    SET_START_AT:               'SET_START_AT',
    LOGIN_ACCEPTED:             'LOGIN_ACCEPTED',
    LOGIN_CLICKED:              'LOGIN_CLICKED',
    LOGIN_DENIED_BAD_DETAILS:   'LOGIN_DENIED_BAD_DETAILS',
    LOGIN_DENIED_NOT_EXIST:     'LOGIN_DENIED_NOT_EXIST',
    LOGIN_MODAL_CLOSED:         'LOGIN_MODAL_CLOSED',
    LOGOUT_USER:                'LOGOUT_USER',
    LOGIN_FORM_UPDATE_USERNAME: 'LOGIN_FORM_UPDATE_USERNAME',
    LOGIN_FORM_UPDATE_PASSWORD: 'LOGIN_FORM_UPDATE_PASSWORD',

    /* Registration */
    CREATE_NAME_TOO_SHORT:      'CREATE_NAME_TOO_SHORT',
    CREATE_NAME_TOO_LONG:       'CREATE_NAME_TOO_LONG',
    CREATE_NAME_BAD_CHARACTERS: 'CREATE_NAME_BAD_CHARACTERS',
    CREATE_PASS_TOO_SHORT:      'CREATE_PASS_TOO_SHORT',
    CREATE_EMAIL_TOO_SHORT:     'CREATE_EMAIL_TOO_SHORT',
    CREATE_NOT_EMAIL_ADDRESS:   'CREATE_NOT_EMAIL_ADDRESS',

    /* Webcams */
    SET_EASYRTC_ID:             'SET_EASYRTC_ID',

    /* Settings */
    HIDE_BANNER:                'HIDE_BANNER',
    SHOW_BANNER:                'SHOW_BANNER',
    TOGGLE_FLUID:               'TOGGLE_FLUID',
    TOGGLE_BANNER:              'TOGGLE_BANNER',
    TOGGLE_WEBCAMS:             'TOGGLE_WEBCAMS',
    SET_WEBCAM_BANDWIDTH:       'SET_WEBCAM_BANDWIDTH',
    SET_SITEBAR_BG_COLOR:       'SET_SITEBAR_BG_COLOR',
    SET_BODY_BG_COLOR:          'SET_BODY_BG_COLOR',
    HIDE_BODY_BG_PICKER:        'HIDE_BODY_BG_PICKER',
    HIDE_SITEBAR_BG_PICKER:     'HIDE_SITEBAR_BG_PICKER',
    SHOW_BODY_BG_PICKER:        'SHOW_BODY_BG_PICKER',
    SHOW_SITEBAR_BG_PICKER:     'SHOW_SITEBAR_BG_PICKER',
    SETTINGS_MODAL_CLOSED:      'SETTINGS_MODAL_CLOSED',

    /* Messaging */
    SEND_CHAT_MESSAGE:          'SEND_CHAT_MESSAGE',
    SEND_PRIVATE_MESSAGE:       'SEND_PRIVATE_MESSAGE',
    SERVER_BROADCAST_MESSAGE:   'SERVER_BROADCAST_MESSAGE',
    SERVER_PRIVATE_MESSAGE:     'SERVER_PRIVATE_MESSAGE',

    /* Rooms */
    JOIN_ROOM:                  'JOIN_ROOM',
    LEAVE_ROOM:                 'LEAVE_ROOM',
    REQUEST_CHANGE_ROOM:        'REQUEST_CHANGE_ROOM',
    ROOM_INFO_UPDATE:           'ROOM_INFO_UPDATE',
    ROOM_STAT_CHANGE:           'ROOM_STAT_CHANGE',
    ROOM_USER_ENTERS:           'ROOM_USER_ENTERS',
    ROOM_USER_LEAVES:           'ROOM_USER_LEAVES',
    ROOM_USER_MESSAGE:          'ROOM_USER_MESSAGE',
    ROOM_CLEAR_MESSAGES:        'ROOM_CLEAR_MESSAGES',
    ROOM_BROADCAST:             'ROOM_BROADCAST',
    ROOM_CREATED:               'ROOM_CREATED',
    ROOM_DESTROYED:             'ROOM_DESTROYED',
    ROOM_UPDATED:               'ROOM_UPDATED',
    ROOM_LIST_UPDATE:           'ROOM_LIST_UPDATE',
    ROOM_PLAYLIST_UPDATE:       'ROOM_PLAYLIST_UPDATE',

    /* Add media modal, authorize video -> add token flow */
    ADD_MEDIA_INPUT:            'ADD_MEDIA_INPUT',
    VALIDATION_RESPONSE:        'VALIDATION_RESPONSE',
    REQUEST_VALIDATION_FOR_URL: 'REQUEST_VALIDATION_FOR_URL',
    VALIDATION_FAILED:          'VALIDATION_FAILED',
    VALIDATION_SUCCEEDED:       'VALIDATION_SUCCEEDED',
    REQUEST_ADD_MEDIA_BY_KEY:   'REQUEST_ADD_MEDIA_BY_KEY',
    REQUEST_ADD_MEDIA_BY_URL:   'REQUEST_ADD_MEDIA_BY_URL',
    REQUEST_ADD_YOUTUBE_VIDEO:  'REQUEST_ADD_YOUTUBE_VIDEO',
    ADD_MEDIA_CLICK:            'ADD_MEDIA_CLICK',
    ADD_MEDIA_MODAL_CLOSED:     'ADD_MEDIA_MODAL_CLOSED',
    RESULT_MESSAGE:             'RESULT_MESSAGE',

    ACCOUNT_BUTTON_CLICKED:     'ACCOUNT_BUTTON_CLICKED',
    CURRENT_MEDIA_ITEM_INFO:    'CURRENT_MEDIA_ITEM_INFO',
    SYSTEM_MESSAGE:             'SYSTEM_MESSAGE',
    TOGGLE_PLAYER:              'TOGGLE_PLAYER',
    SET_PLAYER_WIDTH:           'SET_PLAYER_WIDTH',
    PLAYLIST_UPDATE:            'PLAYLIST_UPDATE',
    PLAYLIST_SKIP_REQUEST:      'PLAYLIST_SKIP_REQUEST',
    PLAYLIST_EXCHANGE_REQUEST:  'PLAYLIST_EXCHANGE_REQUEST',
    PLAYLIST_SHUFFLE_REQUEST:   'PLAYLIST_SHUFFLE_REQUEST',
    PLAYLIST_ITEM_ADDED:        'PLAYLIST_ITEM_ADDED',
    PLAYLIST_ITEM_REMOVED:      'PLAYLIST_ITEM_REMOVED',
    PLAYLIST_ITEM_MOVED:        'PLAYLIST_ITEM_MOVED',
    ROOM_MEDIA_UPDATE:          'ROOM_MEDIA_UPDATE',
    REQUEST_LOGOUT:             'REQUEST_LOGOUT',
    REQUEST_DELETE_PLAYLIST_ENTRY: 'REQUEST_DELETE_PLAYLIST_ENTRY',
    REQUEST_DRAGNDROP_PLAYLIST_ENTRY: 'REQUEST_DRAGNDROP_PLAYLIST_ENTRY',
    EMOTICON_LIST_UPDATE:       'EMOTICON_LIST_UPDATE',
    EMOTICON_ADDED:             'EMOTICON_ADDED',
    EMOTICON_REMOVED:           'EMOTICON_REMOVED',
    SERVER_REBOOT_PENDING:      'SERVER_REBOOT_PENDING',
    DISCONNECTED_WITH_REASON:   'DISCONNECTED_WITH_REASON',
    REGISTRATION_ATTEMPT:       'REGISTRATION_ATTEMPT',
    SET_CHAT_INPUT:             'SET_CHAT_INPUT',
    SET_ROOM_LIST:              'SET_ROOM_LIST',

    //Start Search
    SEARCH_NEW_SEARCH:                  'SEARCH_NEW_SEARCH',
    SEARCH_RESET:                       'SEARCH_RESET',
    SEARCH_RECEIVED_YOUTUBE_RESULTS:    'SEARCH_RECEIVED_YOUTUBE_RESULTS',
    SEARCH_FAILED_YOUTUBE_SEARCH:       'SEARCH_FAILED_YOUTUBE_SEARCH'
    //End Search
}
